untyped

global function CLPrecache_Init

function CLPrecache_Init()
{
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_a" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_b" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_c" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_a" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_b" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_c" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_a" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_b" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_c" )

	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_orange_a" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_orange_b" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_orange_c" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_blue_a" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_blue_b" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_blue_c" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_grey_a" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_grey_b" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_grey_c" )

	VPKNotifyFile( "cfg/startup.cfg" )
	VPKNotifyFile( "cfg/startup_retail.cfg" )

	//PlayerStatusCounts
	PrecacheHUDMaterial( $"ui/icon_status_pilot_enemy" )
	PrecacheHUDMaterial( $"ui/icon_status_titan_enemy" )
	PrecacheHUDMaterial( $"ui/icon_status_burncard_enemy" )
	PrecacheHUDMaterial( $"ui/icon_status_pilot_friendly" )
	PrecacheHUDMaterial( $"ui/icon_status_titan_friendly" )
	PrecacheHUDMaterial( $"ui/icon_status_titan_neutral" )
	PrecacheHUDMaterial( $"ui/icon_status_burncard_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/hud_hex_8v8_bg_left" )


	//MFD stuff. Long term need a better way to gamemode specific precaches
	PrecacheParticleSystem( $"P_RNK" )
	PrecacheParticleSystem( $"P_MFD" )
	PrecacheParticleSystem( $"P_MFD_unmark" )
	PrecacheHUDMaterial( $"vgui/HUD/mfd_pre_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/mfd_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/mfd_enemy" )

	// Sp Precaches
	PrecacheHUDMaterial( $"vgui/HUD/soop/hud_objective_ship" )
	PrecacheHUDMaterial( $"vgui/HUD/soop/soop_char_icon_mac" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p1" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p2" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p3" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p4" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_brp_f" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_brp_m" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_cqp_f" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_cqp_m" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_dmp_f" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_dmp_m" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_atlas" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_ogre" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_stryder" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_spectre" )

	// Coop Precaches
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_titan" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_nuke_titan_square" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_mortar_titan_square" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_emp_titan_square" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p1" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p2" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p3" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_frame_p4" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_brp_f" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_brp_m" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_cqp_f" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_cqp_m" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_dmp_f" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_dmp_m" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_atlas" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_ogre" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_stryder" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_char_spectre" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_ammo_locker_icon" )
	PrecacheHUDMaterial( $"ui/td_wave_icon_mortartitan" )
	PrecacheHUDMaterial( $"ui/td_wave_icon_emptitan" )
	PrecacheHUDMaterial( $"ui/td_wave_icon_cloaked_drone" )
	PrecacheHUDMaterial( $"ui/td_wave_icon_spectre" )
	PrecacheHUDMaterial( $"ui/td_wave_icon_suicide" )
	PrecacheHUDMaterial( $"ui/td_wave_icon_sniper" )
	PrecacheHUDMaterial( $"vgui/hud/coop/wave_callout_strip" )
	PrecacheHUDMaterial( $"vgui/hud/coop/wave_callout_strip_lines" )
	PrecacheHUDMaterial( $"vgui/hud/coop/wave_callout_hazard" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_hex_line_bg_left" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_hex_bg_left" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_hex_left" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_hex_line_left" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_score_strip_coop" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_score_strip_bg_coop" )
	PrecacheHUDMaterial( $"vgui/hud/coop/score_notification_flare" )
	PrecacheHUDMaterial( $"vgui/hud/coop/hud_hex_8v8_bg_left" )
	PrecacheHUDMaterial( $"vgui/hud/coop/icon_status_dead" )
	PrecacheHUDMaterial( $"vgui/hud/coop/mini_turret_counter" )

	//Survivor precache
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_harvester" )
	PrecacheHUDMaterial( $"vgui/HUD/coop/coop_harvester_enemy" )

	//Bomb precache
	PrecacheHUDMaterial( $"r2_ui/hud/gametype_icons/bomb/bomb_neutral" )
	PrecacheHUDMaterial( $"r2_ui/hud/gametype_icons/bomb/bomb_defend" )
	PrecacheHUDMaterial( $"r2_ui/hud/gametype_icons/bomb/bomb_attack" )
	PrecacheHUDMaterial( $"r2_ui/hud/gametype_icons/bomb/bomb_attack_bg" )
	PrecacheHUDMaterial( $"r2_ui/hud/gametype_icons/bomb/bomb_defend_bg" )
	PrecacheHUDMaterial( $"r2_ui/hud/gametype_icons/bomb/bomb_neutral_bg" )

	//Push precache
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_a" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_a_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_a_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_a" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_a_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_a_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_b" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_b_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_b_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_b" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_b_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_b_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_c" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_c_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_c" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_c_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_d" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_d_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_d_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_e" )
	PrecacheHUDMaterial( $"vgui/HUD/push_attack_e_enemy" )
	PrecacheHUDMaterial( $"vgui/HUD/push_defend_e_friendly" )

	//LH Precache
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_grey_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_grey_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_grey_c_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_blue_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_blue_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_blue_c_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_orange_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_orange_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_round_orange_c_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_c_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_d_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_blue_e_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_c_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_d_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_grey_e_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_c_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_d_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_orange_e_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_a_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_b_locked" )
	PrecacheHUDMaterial( $"vgui/HUD/capture_point_status_c_locked" )

	//Rodeo Battery
	PrecacheHUDMaterial( $"vgui/HUD/battery/battery_capture_friendly" )
	PrecacheHUDMaterial( $"vgui/HUD/battery/battery_capture_enemy" )
}
